### ISSUE TITLE
[All_Document_Reader_1718172426840.pdf](https://github.com/user-attachments/files/15845852/All_Document_Reader_1718172426840.pdf)

### ISSUE THREAD

**Issue by ghost** [Automattic/gravatar#17]
[All_Document_Reader_1718172426840.pdf](https://github.com/admin-attachments/files/15845852/All_Document_Reader_1718172426840.pdf)

_Originally posted by @ashleykb95 in https://github.com/Automattic/gravatar/discussions/7_
```[tasklist]
### Tasks
- [x] https://github.com/Automattic/gravatar/pull/14
- [x] https://github.com/Automattic/gravatar/pull/13
- [x] https://github.com/Automattic/gravatar/pull/11
- [x] https://github.com/Automattic/gravatar/issues/15
- [x] https://github.com/Automattic/gravatar/pull/8
```

```[tasklist]
### Tasks
```
